### ISSUE TITLE
[Updates] Should let the user update the SS.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#171] opened 2016-03-06 14:54 UTC
Improvement: Let the user an option to update SS. Would be nice if it shows the versions too. "You have Subutai 4.xx. New version is 5.x.x. Continue update? 'Y/n'

**Comment by Dilshat** [comment] 2016-03-13 07:30
This issue is blocked by https://github.com/subutai-io/base/issues/167

**Comment by eabyshev** [comment] 2016-05-24 04:20
duplicate of #812

**Closed by eabyshev** 2016-05-24 04:20 UTC
Labels: enhancement
