### ISSUE TITLE
[Resource Hosts/Rename] Having an Error while trying to rename my RH

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1774] opened 2017-03-09 08:04 UTC
![image](https://cloud.githubusercontent.com/assets/17665678/23741074/e9847e14-04d0-11e7-981c-b2cb3c05d8a2.png)
To play the bug go to : 
1. Resource Hosts
2. Rename
Result: 
Error message appears, though RH's name changes. 
![image](https://cloud.githubusercontent.com/assets/17665678/23741116/22d16b82-04d1-11e7-85ef-0d43a5f4405e.png)
But maybe its because of Subutai's version and things..

**Comment by Dilshat** [comment] 2017-03-09 08:11
@akylbekesenaliev  Can you attach karaf.log please?

**Comment by Dilshat** [comment] 2017-03-09 08:36
I can not reproduce this error on last RH and MH.
Can you please try on similar setup?

**Comment by akylbekesenaliev** [comment] 2017-03-10 03:42
@Dilshat I am still having it for some reason : 
![image](https://cloud.githubusercontent.com/assets/17665678/23781191/ba2747b4-0575-11e7-9b31-0d1e67a92089.png)
[karaflogs2017-03-10 09-41-46.txt](https://github.com/subutai-io/base/files/832919/karaflogs2017-03-10.09-41-46.txt)

**Comment by Dilshat** [comment] 2017-03-10 03:57
`2017-03-10 03:40:30,874 | DEBUG | tp1766752893-276 | CommandProcessor                 | 190 - io.subutai.core.executor.impl - 4.0.15.SNAPSHOT | Sending:
{
  "request": {
    "type": "EXECUTE_REQUEST",
    "id": "ED05C904125E930CB5B468E427593CD2A986615A",
    "commandId": "0ff1af74-f208-400d-9914-62f54cf5fcb4",
    "workingDirectory": "/",
    "command": "subutai hostname Zinkistan",
    "stdOut": "RETURN",
    "stdErr": "RETURN",
    "runAs": "root",
    "timeout": 30,
    "isDaemon": 0
  }
}

2017-03-10 03:40:31,608 | DEBUG | tp1766752893-242 | CommandProcessor                 | 190 - io.subutai.core.executor.impl - 4.0.15.SNAPSHOT | Response: ResponseImpl[type=EXECUTE_RESPONSE,id=ED05C904125E930CB5B468E427593CD2A986615A,commandId=0ff1af74-f208-400d-9914-62f54cf5fcb4,pid=0,responseNumber=1,stdOut=<null>,stdErr=time="2017-03-10 03:40:31" level=fatal msg="Setting host hostname, exit status 1" 
,exitCode=1]`

**Comment by Dilshat** [comment] 2017-03-10 03:59
Seems error on subos level, @soffokl can you take a look please?
@akylbekesenaliev are you using latest version of software?

**Comment by akylbekesenaliev** [comment] 2017-03-10 04:06
@Dilshat yes, re-installed it yesterday
![image](https://cloud.githubusercontent.com/assets/17665678/23781576/885f666e-0578-11e7-8d50-4b0d847d8443.png)
Have updated it this morning, btw speaking of Updates , having an endless Update availability: 
Everytime I click the Check item I get an available Update and when I update it it kinda gets updated really fast like in 10 seconds, and then it says *Success* but as you can see on the picture no changes are brought by Updates: 
![image](https://cloud.githubusercontent.com/assets/17665678/23781650/0200ba90-0579-11e7-8107-45a42a989ee2.png)

![image](https://cloud.githubusercontent.com/assets/17665678/23781595/bf4cd03a-0578-11e7-8297-105b09678d1e.png)

**Comment by Dilshat** [comment] 2017-03-10 04:08
Seems you are having some problems with your setup. please contact @soffokl

**Comment by akylbekesenaliev** [comment] 2017-03-15 05:47
Tested this issue again , but no changes came, still having this error: 

Test #1 : 
Reimported management  - 
1. sudo subutai destroy management
2. sudo subutai import management 
Result : Still having this error 

Test #2: 
Reinstalled Subutai - deleted Subutai and installed a fresh one, performed the steps but still having this error. 
Result: Still having this error

@Dilshat @soffokl

**Comment by akylbekesenaliev** [comment] 2017-03-15 06:14
Comment from @soffokl : 
*it's looks like your problem with changing hostname related to the old versions of OS and agent
migration to the core16 should solve it.*
Gonna be testing this issue after migration to the core16, for now this issue is frozen.

**Comment by Dilshat** [comment] 2017-03-15 06:15
Closing since the env is outdated.

**Closed by Dilshat** 2017-03-15 06:15 UTC
Labels: bug
