### ISSUE TITLE
Environment with elastic search template is not seen on the Subutai side

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1036] opened 2016-06-11 09:20 UTC
I have created 4 environments using 4 different templates and only 3 of them are seen on the Subutai side:
![subutai elastic none](https://cloud.githubusercontent.com/assets/17665678/15984308/c7d2084a-2fce-11e6-88b9-bb30123bd7c2.png)
but when I go to Hub all the 4 environments are seen:
![elastic hub](https://cloud.githubusercontent.com/assets/17665678/15984312/df17023a-2fce-11e6-9a8d-f7c70db780ff.png)

**Comment by soffokl** [comment] 2016-06-11 09:23
@akylbekesenaliev no containers in your environment on screenshot.

**Comment by akylbekesenaliev** [comment] 2016-06-11 09:26
ok, so in this case environment won't be seen from the Hub side?

**Comment by Dilshat** [comment] 2016-06-11 09:29
this question is for @asanaliev

**Comment by asanaliev** [comment] 2016-06-12 23:52
@akylbekesenaliev can you explain how you created that elasticsearch environment without containers?
For example, Hub doesn't allow creating env without containers. So may be, you created env with containers first, then deleted those containers?

Please also try to reproduce this case. I couldn't reproduce myself. May be it was some intermittent bug that has been fixed with recent changes. Let's check.

**Comment by akylbekesenaliev** [comment] 2016-06-13 07:37
@asanaliev I have followed the steps in the scenario for the elastic search and did nothing else...
Right now I cant reproduce it having this error:
![image](https://cloud.githubusercontent.com/assets/17665678/16000089/ad05daf2-3152-11e6-99db-1247ddcf6e67.png)
also just now Subutai stopped working, going to restart it ...

**Comment by akylbekesenaliev** [comment] 2016-06-13 09:09
@asanaliev 
![image](https://cloud.githubusercontent.com/assets/17665678/16002219/24ed3766-315f-11e6-84bb-c4634e843f3c.png)
I have successfully created an environment with the elastic search template and it also can be seen from the Hub side:
![image](https://cloud.githubusercontent.com/assets/17665678/16002249/55161bec-315f-11e6-8df2-bdbc4fb84972.png)
and I am suppose to have 3 containers and I do, and it can be seen here:
![image](https://cloud.githubusercontent.com/assets/17665678/16002270/75906828-315f-11e6-9dee-a9ed0dc4584a.png)
But the Hub shows me only 1 container:
![image](https://cloud.githubusercontent.com/assets/17665678/16002298/94d07ba6-315f-11e6-8eae-37a894b27c6c.png)

**Comment by Dilshat** [comment] 2016-06-13 09:51
@akylbekesenaliev can you reproduce this with last SS?

**Comment by akylbekesenaliev** [comment] 2016-06-13 10:46
@Dilshat yes I will try

**Comment by akylbekesenaliev** [comment] 2016-06-14 06:05
@Dilshat I have tested this with the lates SS :
![image](https://cloud.githubusercontent.com/assets/17665678/16032491/d9366440-320e-11e6-9815-a2e8a1220b55.png)
The environment is succesfully created and cluster too :
But the Hub shows me that I only have one container which is not true I have 3 of them :
![image](https://cloud.githubusercontent.com/assets/17665678/16032524/16c5d85e-320f-11e6-92fd-10db6d55de7b.png)
Here:
![image](https://cloud.githubusercontent.com/assets/17665678/16032534/2b3fbd4a-320f-11e6-8721-15ca1ec80f13.png)

**Comment by asanaliev** [comment] 2016-06-14 18:28
I could not reproduce this issue:
1. Created env on Hub with three ES containers. Can see containers on SS.
2. Vice versa: created same kind of env on SS and can see on Hub. 

@akylbekesenaliev Pls ping next when you have this issues. I will debug your environment.

**Comment by akylbekesenaliev** [comment] 2016-06-15 04:54
@asanaliev I no more have this issue,I think it was gone with the last update maybe, but as you can see from the comments above a new issue was found and thats why I keep this issue Open.

**Closed** 2016-06-15 12:36 UTC
Labels: bug
